// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

function createDinero(options) {
  let calculator = options.calculator;
  let defaultFormatter_toNumber = param => 0.0;
  let defaultFormatter_toString = param => "";
  let defaultFormatter = {
    toNumber: defaultFormatter_toNumber,
    toString: defaultFormatter_toString
  };
  let actualFormatter = Stdlib_Option.getOr(options.formatter, defaultFormatter);
  return dineroOptions => {
    let currency = dineroOptions.currency;
    let exponent = currency.exponent;
    let base = currency.base;
    let code = currency.code;
    let amount = dineroOptions.amount;
    let actualScale = Stdlib_Option.getOr(dineroOptions.scale, exponent);
    let callback = options.onCreate;
    if (callback !== undefined) {
      callback({
        amount: amount,
        currency: {
          code: code,
          base: base,
          exponent: exponent
        },
        scale: Primitive_option.some(actualScale)
      });
    }
    let createFn = opts => {
      let factory = createDinero({
        calculator: calculator,
        formatter: options.formatter,
        onCreate: options.onCreate
      });
      return factory(opts);
    };
    return {
      calculator: calculator,
      formatter: actualFormatter,
      create: createFn,
      toJSON: () => ({
        amount: amount,
        currency: {
          code: code,
          base: base,
          exponent: exponent
        },
        scale: actualScale
      })
    };
  };
}

export {
  createDinero,
}
/* No side effect */
