// Generated by ReScript, PLEASE EDIT WITH CARE

import * as EqualUtil from "../utils/equalUtil.js";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as NormalizeScale from "./normalizeScale.js";

function haveSameAmount(calculator) {
  let normalizeFn = NormalizeScale.normalizeScale(calculator);
  let equalFn = EqualUtil.equal(calculator);
  return dineroObjects => {
    let normalized = normalizeFn(dineroObjects);
    if (normalized.length <= 1) {
      return true;
    }
    let firstDinero = Stdlib_Option.getOrThrow(normalized[0], undefined);
    let otherDineros = normalized.slice(1);
    let match = firstDinero.toJSON();
    let comparatorAmount = match.amount;
    return otherDineros.every(d => {
      let match = d.toJSON();
      return equalFn(match.amount, comparatorAmount);
    });
  };
}

export {
  haveSameAmount,
}
/* No side effect */
