// Generated by ReScript, PLEASE EDIT WITH CARE

import * as MinimumUtil from "../utils/minimumUtil.js";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as NormalizeScale from "./normalizeScale.js";
import * as Stdlib_JsError from "@rescript/runtime/lib/es6/Stdlib_JsError.js";
import * as HaveSameCurrency from "./haveSameCurrency.js";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

function unsafeMinimum(calculator) {
  let minFn = MinimumUtil.minimum(calculator);
  return dineroObjects => {
    let firstDinero = Stdlib_Option.getOrThrow(dineroObjects[0], undefined);
    let match = firstDinero.toJSON();
    let amounts = dineroObjects.map(subject => subject.toJSON().amount);
    let amount = minFn(amounts);
    return firstDinero.create({
      amount: amount,
      currency: match.currency,
      scale: Primitive_option.some(match.scale)
    });
  };
}

function safeMinimum(calculator) {
  let normalizeFn = NormalizeScale.normalizeScale(calculator);
  let minFn = unsafeMinimum(calculator);
  return dineroObjects => {
    let condition = HaveSameCurrency.haveSameCurrency(dineroObjects);
    if (!condition) {
      Stdlib_JsError.throwWithMessage("Objects must have the same currency.");
    }
    return minFn(normalizeFn(dineroObjects));
  };
}

export {
  unsafeMinimum,
  safeMinimum,
}
/* No side effect */
