// Generated by ReScript, PLEASE EDIT WITH CARE

import * as TransformScale from "./transformScale.js";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

function multiply(calculator) {
  let convertScaleFn = TransformScale.transformScale(calculator);
  let zero = calculator.zero();
  return (multiplicand, multiplier) => {
    let match = multiplicand.toJSON();
    let newScale = calculator.add(match.scale, zero);
    return convertScaleFn(multiplicand.create({
      amount: calculator.multiply(match.amount, multiplier),
      currency: match.currency,
      scale: Primitive_option.some(newScale)
    }), newScale, undefined, undefined);
  };
}

export {
  multiply,
}
/* No side effect */
