// Generated by ReScript, PLEASE EDIT WITH CARE

import * as IsArray from "../utils/isArray.js";
import * as ToUnits from "./toUnits.js";
import * as Absolute from "../utils/absolute.js";
import * as EqualUtil from "../utils/equalUtil.js";
import * as ComputeBase from "../utils/computeBase.js";
import * as LessThanUtil from "../utils/lessThanUtil.js";
import * as Stdlib_Array from "@rescript/runtime/lib/es6/Stdlib_Array.js";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as Stdlib_JsError from "@rescript/runtime/lib/es6/Stdlib_JsError.js";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

function getDecimal(calculator, formatter) {
  let absoluteFn = Absolute.absolute(calculator);
  let equalFn = EqualUtil.equal(calculator);
  let lessThanFn = LessThanUtil.lessThan(calculator);
  let zero = calculator.zero();
  return (units, scale) => {
    let whole = formatter.toString(Primitive_option.some(Stdlib_Option.getOrThrow(units[0], undefined)));
    let fractional = formatter.toString(Primitive_option.some(absoluteFn(Stdlib_Option.getOrThrow(units[1], undefined))));
    let scaleNumber = formatter.toNumber(Primitive_option.some(scale)) | 0;
    let paddedFractional = fractional.padStart(scaleNumber, "0");
    let decimal = whole + `.` + paddedFractional;
    let leadsWithZero = equalFn(Stdlib_Option.getOrThrow(units[0], undefined), zero);
    let isNegative = lessThanFn(Stdlib_Option.getOrThrow(units[1], undefined), zero);
    if (leadsWithZero && isNegative) {
      return `-` + decimal;
    } else {
      return decimal;
    }
  };
}

function toDecimal(calculator) {
  let toUnitsFn = ToUnits.toUnits(calculator);
  let computeBaseFn = ComputeBase.computeBase(calculator);
  let equalFn = EqualUtil.equal(calculator);
  return (dineroObject, transformer) => {
    let match = dineroObject.toJSON();
    let currency = match.currency;
    let base = computeBaseFn(ComputeBase.fromValue(currency.base));
    let zero = calculator.zero();
    let ten = Stdlib_Array.reduce(Stdlib_Array.make(10, undefined), zero, (acc, param) => calculator.increment(acc));
    let isMultiBase = IsArray.isArray(currency.base);
    let isBaseTen = equalFn(calculator.modulo(base, ten), zero);
    let isDecimal = !isMultiBase && isBaseTen;
    if (!isDecimal) {
      Stdlib_JsError.throwWithMessage("Cannot format a non-decimal currency to decimal.");
    }
    let units = toUnitsFn(dineroObject, undefined);
    let getDecimalFn = getDecimal(calculator, dineroObject.formatter);
    let value = getDecimalFn(units, match.scale);
    if (transformer !== undefined) {
      return transformer({
        value: value,
        currency: currency
      });
    } else {
      return value;
    }
  };
}

export {
  getDecimal,
  toDecimal,
}
/* No side effect */
