// Generated by ReScript, PLEASE EDIT WITH CARE

import * as GetDivisors from "../utils/getDivisors.js";

function toUnits(calculator) {
  GetDivisors.getDivisors(calculator);
  return (dineroObject, transformer) => {
    let match = dineroObject.toJSON();
    let currency = match.currency;
    let amount = match.amount;
    let base = currency.base;
    let divisor = calculator.power(base, match.scale);
    let quotient = calculator.integerDivide(amount, divisor);
    let remainder = calculator.modulo(amount, divisor);
    let value = [
      quotient,
      remainder
    ];
    if (transformer !== undefined) {
      return transformer({
        value: value,
        currency: currency
      });
    } else {
      return value;
    }
  };
}

export {
  toUnits,
}
/* No side effect */
