// Generated by ReScript, PLEASE EDIT WITH CARE

import * as EqualUtil from "../utils/equalUtil.js";
import * as ComputeBase from "../utils/computeBase.js";
import * as MaximumUtil from "../utils/maximumUtil.js";
import * as TransformScale from "./transformScale.js";
import * as CountTrailingZeros from "../utils/countTrailingZeros.js";

function trimScale(calculator) {
  let countTrailingZerosFn = CountTrailingZeros.countTrailingZeros(calculator);
  let equalFn = EqualUtil.equal(calculator);
  let maximumFn = MaximumUtil.maximum(calculator);
  let transformScaleFn = TransformScale.transformScale(calculator);
  let computeBaseFn = ComputeBase.computeBase(calculator);
  return dineroObject => {
    let match = dineroObject.toJSON();
    let scale = match.scale;
    let currency = match.currency;
    let base = computeBaseFn(ComputeBase.fromValue(currency.base));
    let trailingZerosLength = countTrailingZerosFn(match.amount, base);
    let difference = calculator.subtract(scale, trailingZerosLength);
    let newScale = maximumFn([
      difference,
      currency.exponent
    ]);
    if (equalFn(newScale, scale)) {
      return dineroObject;
    } else {
      return transformScaleFn(dineroObject, newScale, undefined, undefined);
    }
  };
}

export {
  trimScale,
}
/* No side effect */
