// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Api from "./api/api.js";

let calculator = {
  add: Api.add,
  compare: Api.compare,
  decrement: Api.decrement,
  increment: Api.increment,
  integerDivide: Api.integerDivide,
  modulo: Api.modulo,
  multiply: Api.multiply,
  power: Api.power,
  subtract: Api.subtract,
  zero: Api.zero
};

let add = Api.add;

let compare = Api.compare;

let decrement = Api.decrement;

let increment = Api.increment;

let integerDivide = Api.integerDivide;

let modulo = Api.modulo;

let multiply = Api.multiply;

let power = Api.power;

let subtract = Api.subtract;

let zero = Api.zero;

export {
  add,
  compare,
  decrement,
  increment,
  integerDivide,
  modulo,
  multiply,
  power,
  subtract,
  zero,
  calculator,
}
/* No side effect */
