// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Calculator from "./calculator.js";

let add = Calculator.add;

let compare = Calculator.compare;

let decrement = Calculator.decrement;

let increment = Calculator.increment;

let integerDivide = Calculator.integerDivide;

let modulo = Calculator.modulo;

let multiply = Calculator.multiply;

let power = Calculator.power;

let subtract = Calculator.subtract;

let zero = Calculator.zero;

let calculator = Calculator.calculator;

export {
  add,
  compare,
  decrement,
  increment,
  integerDivide,
  modulo,
  multiply,
  power,
  subtract,
  zero,
  calculator,
}
/* No side effect */
