// Generated by ReScript, PLEASE EDIT WITH CARE


function compare(a, b) {
  if (a < b) {
    return "LT";
  } else if (a > b) {
    return "GT";
  } else {
    return "EQ";
  }
}

export {
  compare,
}
/* No side effect */
