// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Primitive_bigint from "@rescript/runtime/lib/es6/Primitive_bigint.js";

let integerDivide = Primitive_bigint.div;

export {
  integerDivide,
}
/* No side effect */
