// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Primitive_bigint from "@rescript/runtime/lib/es6/Primitive_bigint.js";

let modulo = Primitive_bigint.mod_;

export {
  modulo,
}
/* No side effect */
