// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Stdlib_JsError from "@rescript/runtime/lib/es6/Stdlib_JsError.js";

function assert(condition, message) {
  if (!condition) {
    return Stdlib_JsError.throwWithMessage("[Dinero.js] " + message);
  }
}

export {
  assert,
}
/* No side effect */
