// Generated by ReScript, PLEASE EDIT WITH CARE

import * as MaximumUtil from "../utils/maximumUtil.js";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as TransformScale from "./transformScale.js";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

function convert(calculator) {
  let convertScaleFn = TransformScale.transformScale(calculator);
  MaximumUtil.maximum(calculator);
  let zero = calculator.zero();
  return (dineroObject, newCurrency, rates) => {
    let rate = Stdlib_Option.getOrThrow(rates[newCurrency.code], undefined);
    let match = dineroObject.toJSON();
    let match$1;
    if (rate.TAG === "ScaledAmount") {
      let scaledAmt = rate._0;
      match$1 = [
        scaledAmt.amount,
        Stdlib_Option.getOr(scaledAmt.scale, zero)
      ];
    } else {
      match$1 = [
        rate._0,
        zero
      ];
    }
    let newScale = calculator.add(match.scale, match$1[1]);
    return convertScaleFn(dineroObject.create({
      amount: calculator.multiply(match.amount, match$1[0]),
      currency: newCurrency,
      scale: Primitive_option.some(newScale)
    }), newScale, undefined, undefined);
  };
}

export {
  convert,
}
/* No side effect */
