// Generated by ReScript, PLEASE EDIT WITH CARE

import * as HaveSameAmount from "./haveSameAmount.js";
import * as HaveSameCurrency from "./haveSameCurrency.js";

function equal(calculator) {
  return (dineroObject, comparator) => {
    if (HaveSameAmount.haveSameAmount(calculator)([
        dineroObject,
        comparator
      ])) {
      return HaveSameCurrency.haveSameCurrency([
        dineroObject,
        comparator
      ]);
    } else {
      return false;
    }
  };
}

export {
  equal,
}
/* No side effect */
