// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as NormalizeScale from "./normalizeScale.js";
import * as Stdlib_JsError from "@rescript/runtime/lib/es6/Stdlib_JsError.js";
import * as GreaterThanUtil from "../utils/greaterThanUtil.js";
import * as HaveSameCurrency from "./haveSameCurrency.js";

function unsafeGreaterThan(calculator) {
  let greaterThanFn = GreaterThanUtil.greaterThan(calculator);
  return (dineroObject, comparator) => {
    let dineroObjects = [
      dineroObject,
      comparator
    ];
    let amounts = dineroObjects.map(d => d.toJSON().amount);
    let subjectAmount = Stdlib_Option.getOrThrow(amounts[0], undefined);
    let comparatorAmount = Stdlib_Option.getOrThrow(amounts[1], undefined);
    return greaterThanFn(subjectAmount, comparatorAmount);
  };
}

function safeGreaterThan(calculator) {
  let normalizeFn = NormalizeScale.normalizeScale(calculator);
  let greaterThanFn = unsafeGreaterThan(calculator);
  return (dineroObject, comparator) => {
    let condition = HaveSameCurrency.haveSameCurrency([
      dineroObject,
      comparator
    ]);
    if (!condition) {
      Stdlib_JsError.throwWithMessage("Objects must have the same currency.");
    }
    let normalized = normalizeFn([
      dineroObject,
      comparator
    ]);
    let subjectAmount = Stdlib_Option.getOrThrow(normalized[0], undefined);
    let comparatorAmount = Stdlib_Option.getOrThrow(normalized[1], undefined);
    return greaterThanFn(subjectAmount, comparatorAmount);
  };
}

export {
  unsafeGreaterThan,
  safeGreaterThan,
}
/* No side effect */
