// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as NormalizeScale from "./normalizeScale.js";
import * as Stdlib_JsError from "@rescript/runtime/lib/es6/Stdlib_JsError.js";
import * as HaveSameCurrency from "./haveSameCurrency.js";
import * as GreaterThanOrEqualUtil from "../utils/greaterThanOrEqualUtil.js";

function unsafeGreaterThanOrEqual(calculator) {
  let greaterThanOrEqualFn = GreaterThanOrEqualUtil.greaterThanOrEqual(calculator);
  return (dineroObject, comparator) => {
    let dineroObjects = [
      dineroObject,
      comparator
    ];
    let amounts = dineroObjects.map(d => d.toJSON().amount);
    let subjectAmount = Stdlib_Option.getOrThrow(amounts[0], undefined);
    let comparatorAmount = Stdlib_Option.getOrThrow(amounts[1], undefined);
    return greaterThanOrEqualFn(subjectAmount, comparatorAmount);
  };
}

function safeGreaterThanOrEqual(calculator) {
  let normalizeFn = NormalizeScale.normalizeScale(calculator);
  let greaterThanOrEqualFn = unsafeGreaterThanOrEqual(calculator);
  return (dineroObject, comparator) => {
    let condition = HaveSameCurrency.haveSameCurrency([
      dineroObject,
      comparator
    ]);
    if (!condition) {
      Stdlib_JsError.throwWithMessage("Objects must have the same currency.");
    }
    let normalized = normalizeFn([
      dineroObject,
      comparator
    ]);
    let subjectAmount = Stdlib_Option.getOrThrow(normalized[0], undefined);
    let comparatorAmount = Stdlib_Option.getOrThrow(normalized[1], undefined);
    return greaterThanOrEqualFn(subjectAmount, comparatorAmount);
  };
}

export {
  unsafeGreaterThanOrEqual,
  safeGreaterThanOrEqual,
}
/* No side effect */
