// Generated by ReScript, PLEASE EDIT WITH CARE

import * as EqualUtil from "../utils/equalUtil.js";
import * as ComputeBase from "../utils/computeBase.js";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";

function haveSameCurrency(dineroObjects) {
  if (dineroObjects.length <= 1) {
    return true;
  }
  let firstDinero = Stdlib_Option.getOrThrow(dineroObjects[0], undefined);
  let otherDineros = dineroObjects.slice(1);
  let computeBaseFn = ComputeBase.computeBase(firstDinero.calculator);
  let match = firstDinero.toJSON();
  let comparator = match.currency;
  let equalFn = EqualUtil.equal(firstDinero.calculator);
  let comparatorBase = computeBaseFn(ComputeBase.fromValue(comparator.base));
  return otherDineros.every(d => {
    let match = d.toJSON();
    let subject = match.currency;
    let subjectBase = computeBaseFn(ComputeBase.fromValue(subject.base));
    if (subject.code === comparator.code && equalFn(subjectBase, comparatorBase)) {
      return equalFn(subject.exponent, comparator.exponent);
    } else {
      return false;
    }
  });
}

export {
  haveSameCurrency,
}
/* No side effect */
