// Generated by ReScript, PLEASE EDIT WITH CARE

import * as LessThanUtil from "../utils/lessThanUtil.js";

function isNegative(calculator) {
  let lessThanFn = LessThanUtil.lessThan(calculator);
  return dineroObject => {
    let match = dineroObject.toJSON();
    return lessThanFn(match.amount, calculator.zero());
  };
}

export {
  isNegative,
}
/* No side effect */
