// Generated by ReScript, PLEASE EDIT WITH CARE

import * as GreaterThanUtil from "../utils/greaterThanUtil.js";

function isPositive(calculator) {
  let greaterThanFn = GreaterThanUtil.greaterThan(calculator);
  return dineroObject => {
    let match = dineroObject.toJSON();
    return greaterThanFn(match.amount, calculator.zero());
  };
}

export {
  isPositive,
}
/* No side effect */
