// Generated by ReScript, PLEASE EDIT WITH CARE

import * as EqualUtil from "../utils/equalUtil.js";

function isZero(calculator) {
  let equalFn = EqualUtil.equal(calculator);
  return dineroObject => {
    let match = dineroObject.toJSON();
    return equalFn(match.amount, calculator.zero());
  };
}

export {
  isZero,
}
/* No side effect */
