// Generated by ReScript, PLEASE EDIT WITH CARE

import * as EqualUtil from "../utils/equalUtil.js";
import * as MaximumUtil from "../utils/maximumUtil.js";
import * as Stdlib_Array from "@rescript/runtime/lib/es6/Stdlib_Array.js";
import * as TransformScale from "./transformScale.js";

function normalizeScale(calculator) {
  let maximumFn = MaximumUtil.maximum(calculator);
  let convertScaleFn = TransformScale.transformScale(calculator);
  let equalFn = EqualUtil.equal(calculator);
  return dineroObjects => {
    let highestScale = Stdlib_Array.reduce(dineroObjects, calculator.zero(), (highest, current) => {
      let match = current.toJSON();
      return maximumFn([
        highest,
        match.scale
      ]);
    });
    return dineroObjects.map(d => {
      let match = d.toJSON();
      if (equalFn(match.scale, highestScale)) {
        return d;
      } else {
        return convertScaleFn(d, highestScale, undefined, undefined);
      }
    });
  };
}

export {
  normalizeScale,
}
/* No side effect */
