// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as NormalizeScale from "./normalizeScale.js";
import * as Stdlib_JsError from "@rescript/runtime/lib/es6/Stdlib_JsError.js";
import * as HaveSameCurrency from "./haveSameCurrency.js";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

function unsafeSubtract(calculator) {
  return (minuend, subtrahend) => {
    let match = minuend.toJSON();
    let match$1 = subtrahend.toJSON();
    let amount = calculator.subtract(match.amount, match$1.amount);
    return minuend.create({
      amount: amount,
      currency: match.currency,
      scale: Primitive_option.some(match.scale)
    });
  };
}

function safeSubtract(calculator) {
  let normalizeFn = NormalizeScale.normalizeScale(calculator);
  let subtractFn = unsafeSubtract(calculator);
  return (minuend, subtrahend) => {
    let condition = HaveSameCurrency.haveSameCurrency([
      minuend,
      subtrahend
    ]);
    if (!condition) {
      Stdlib_JsError.throwWithMessage("Objects must have the same currency.");
    }
    let normalized = normalizeFn([
      minuend,
      subtrahend
    ]);
    let newMinuend = Stdlib_Option.getOrThrow(normalized[0], undefined);
    let newSubtrahend = Stdlib_Option.getOrThrow(normalized[1], undefined);
    return subtractFn(newMinuend, newSubtrahend);
  };
}

export {
  unsafeSubtract,
  safeSubtract,
}
/* No side effect */
