// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Down from "../divide/down.js";
import * as ComputeBase from "../utils/computeBase.js";
import * as GreaterThanUtil from "../utils/greaterThanUtil.js";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

function transformScale(calculator) {
  let greaterThanFn = GreaterThanUtil.greaterThan(calculator);
  let computeBaseFn = ComputeBase.computeBase(calculator);
  return (dineroObject, newScale, divideOpt, param) => {
    let divide = divideOpt !== undefined ? divideOpt : Down.down;
    let match = dineroObject.toJSON();
    let scale = match.scale;
    let currency = match.currency;
    let amount = match.amount;
    let isLarger = greaterThanFn(newScale, scale);
    let match$1 = isLarger ? [
        newScale,
        scale
      ] : [
        scale,
        newScale
      ];
    let base = computeBaseFn(ComputeBase.fromValue(currency.base));
    let factor = calculator.power(base, calculator.subtract(match$1[0], match$1[1]));
    let newAmount = isLarger ? calculator.multiply(amount, factor) : divide(amount, factor, calculator);
    return dineroObject.create({
      amount: newAmount,
      currency: currency,
      scale: Primitive_option.some(newScale)
    });
  };
}

export {
  transformScale,
}
/* No side effect */
