// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Up from "./up.js";
import * as Down from "./down.js";
import * as IsHalf from "../utils/isHalf.js";
import * as Absolute from "../utils/absolute.js";
import * as GreaterThanUtil from "../utils/greaterThanUtil.js";

function halfUp(amount, factor, calculator) {
  let greaterThanFn = GreaterThanUtil.greaterThan(calculator);
  let isHalfFn = IsHalf.isHalf(calculator);
  let absoluteFn = Absolute.absolute(calculator);
  let zero = calculator.zero();
  let remainder = absoluteFn(calculator.modulo(amount, factor));
  let difference = calculator.subtract(factor, remainder);
  let isLessThanHalf = greaterThanFn(difference, remainder);
  let isPositive = greaterThanFn(amount, zero);
  if (isHalfFn(amount, factor) || isPositive && !isLessThanHalf || !isPositive && isLessThanHalf) {
    return Up.up(amount, factor, calculator);
  } else {
    return Down.down(amount, factor, calculator);
  }
}

export {
  halfUp,
}
/* No side effect */
