// Generated by ReScript, PLEASE EDIT WITH CARE

import * as HalfUp from "./halfUp.js";
import * as IsEven from "../utils/isEven.js";
import * as IsHalf from "../utils/isHalf.js";

function halfOdd(amount, factor, calculator) {
  let isEvenFn = IsEven.isEven(calculator);
  let isHalfFn = IsHalf.isHalf(calculator);
  let rounded = HalfUp.halfUp(amount, factor, calculator);
  if (!isHalfFn(amount, factor) || !isEvenFn(rounded)) {
    return rounded;
  } else {
    return calculator.decrement(rounded);
  }
}

export {
  halfOdd,
}
/* No side effect */
