// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Down from "./down.js";
import * as Sign from "../utils/sign.js";
import * as HalfUp from "./halfUp.js";
import * as IsHalf from "../utils/isHalf.js";
import * as Absolute from "../utils/absolute.js";

function halfTowardsZero(amount, factor, calculator) {
  let signFn = Sign.sign(calculator);
  let isHalfFn = IsHalf.isHalf(calculator);
  let absoluteFn = Absolute.absolute(calculator);
  if (isHalfFn(amount, factor)) {
    return calculator.multiply(signFn(amount), Down.down(absoluteFn(amount), factor, calculator));
  } else {
    return HalfUp.halfUp(amount, factor, calculator);
  }
}

export {
  halfTowardsZero,
}
/* No side effect */
