// Generated by ReScript, PLEASE EDIT WITH CARE

import * as EqualUtil from "../utils/equalUtil.js";
import * as GreaterThanUtil from "../utils/greaterThanUtil.js";

function up(amount, factor, calculator) {
  let greaterThanFn = GreaterThanUtil.greaterThan(calculator);
  let equalFn = EqualUtil.equal(calculator);
  let zero = calculator.zero();
  let isPositive = greaterThanFn(amount, zero);
  let quotient = calculator.integerDivide(amount, factor);
  let remainder = calculator.modulo(amount, factor);
  let isInteger = equalFn(remainder, zero);
  if (!isInteger && isPositive) {
    return calculator.increment(quotient);
  } else {
    return quotient;
  }
}

export {
  up,
}
/* No side effect */
