// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Add from "./add.js";
import * as Zero from "./zero.js";
import * as Power from "./power.js";
import * as Modulo from "./modulo.js";
import * as Compare from "./compare.js";
import * as Multiply from "./multiply.js";
import * as Subtract from "./subtract.js";
import * as Decrement from "./decrement.js";
import * as Increment from "./increment.js";
import * as IntegerDivide from "./integerDivide.js";

let add = Add.add;

let compare = Compare.compare;

let decrement = Decrement.decrement;

let increment = Increment.increment;

let integerDivide = IntegerDivide.integerDivide;

let modulo = Modulo.modulo;

let multiply = Multiply.multiply;

let fromValue = Power.fromValue;

let powerInt = Power.powerInt;

let powerFloat = Power.powerFloat;

let power = Power.power;

let subtract = Subtract.subtract;

let zero = Zero.zero;

export {
  add,
  compare,
  decrement,
  increment,
  integerDivide,
  modulo,
  multiply,
  fromValue,
  powerInt,
  powerFloat,
  power,
  subtract,
  zero,
}
/* No side effect */
