// Generated by ReScript, PLEASE EDIT WITH CARE


function compare(a, b) {
  if (a < b) {
    return -1;
  } else if (a > b) {
    return 1;
  } else {
    return 0;
  }
}

export {
  compare,
}
/* No side effect */
