// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Stdlib_JsError from "@rescript/runtime/lib/es6/Stdlib_JsError.js";

function fromValue(value) {
  if (typeof value === "bigint") {
    return Stdlib_JsError.throwWithMessage("BigInt values not supported in calculator-number. Use calculator-bigint package instead.");
  } else if (typeof value === "number" && value === Math.floor(value)) {
    return {
      NAME: "Int",
      VAL: value
    };
  } else {
    return {
      NAME: "Float",
      VAL: value
    };
  }
}

function powerInt(base, exponent) {
  return Math.pow(base, exponent);
}

function powerFloat(base, exponent) {
  return Math.pow(base, exponent);
}

function power(base, exponent) {
  if (base.NAME === "Float") {
    let b = base.VAL;
    return {
      NAME: "Float",
      VAL: Math.pow(b, exponent.VAL)
    };
  }
  let b$1 = base.VAL;
  if (exponent.NAME === "Float") {
    return {
      NAME: "Float",
      VAL: Math.pow(b$1, exponent.VAL)
    };
  } else {
    return {
      NAME: "Int",
      VAL: Math.pow(b$1, exponent.VAL)
    };
  }
}

export {
  fromValue,
  powerInt,
  powerFloat,
  power,
}
/* No side effect */
