// Generated by ReScript, PLEASE EDIT WITH CARE


let invalidAmountMessage = "Amount is invalid.";

let invalidScaleMessage = "Scale is invalid.";

let invalidRatiosMessage = "Ratios are invalid.";

let unequalScalesMessage = "Objects must have the same scale.";

let unequalCurrenciesMessage = "Objects must have the same currency.";

let nonDecimalCurrencyMessage = "Currency is not decimal.";

export {
  invalidAmountMessage,
  invalidScaleMessage,
  invalidRatiosMessage,
  unequalScalesMessage,
  unequalCurrenciesMessage,
  nonDecimalCurrencyMessage,
}
/* No side effect */
