// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Api from "./api/api.js";

let calculator = {
  add: Api.add,
  compare: Api.compare,
  decrement: Api.decrement,
  increment: Api.increment,
  integerDivide: Api.integerDivide,
  modulo: Api.modulo,
  multiply: Api.multiply,
  power: Api.power,
  subtract: Api.subtract,
  zero: Api.zero
};

export {
  calculator,
}
/* No side effect */
