// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Down from "./down.js";
import * as HalfUp from "./halfUp.js";
import * as IsHalf from "../utils/isHalf.js";

function halfDown(amount, factor, calculator) {
  let isHalfFn = IsHalf.isHalf(calculator);
  if (isHalfFn(amount, factor)) {
    return Down.down(amount, factor, calculator);
  } else {
    return HalfUp.halfUp(amount, factor, calculator);
  }
}

export {
  halfDown,
}
/* No side effect */
