// Generated by ReScript, PLEASE EDIT WITH CARE

import * as IsArray from "./isArray.js";
import * as Js_array from "@rescript/runtime/lib/es6/Js_array.js";
import * as Stdlib_JsError from "@rescript/runtime/lib/es6/Stdlib_JsError.js";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

function computeBase(calculator) {
  return base => {
    if (base.NAME !== "Array") {
      return base.VAL;
    }
    let baseArray = base.VAL;
    let first = baseArray[0];
    if (first === undefined) {
      return Stdlib_JsError.throwWithMessage("baseArray is empty");
    }
    let rest = Js_array.sliceFrom(1, baseArray);
    return Js_array.reduce((acc, curr) => calculator.multiply(acc, curr), Primitive_option.valFromOption(first), rest);
  };
}

function fromValue(value) {
  if (IsArray.isArray(value)) {
    return {
      NAME: "Array",
      VAL: value
    };
  } else {
    return {
      NAME: "Single",
      VAL: value
    };
  }
}

export {
  computeBase,
  fromValue,
}
/* No side effect */
