// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Js_array from "@rescript/runtime/lib/es6/Js_array.js";
import * as EqualUtil from "./equalUtil.js";
import * as LessThanUtil from "./lessThanUtil.js";
import * as Primitive_int from "@rescript/runtime/lib/es6/Primitive_int.js";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as GreaterThanUtil from "./greaterThanUtil.js";
import * as GreaterThanOrEqualUtil from "./greaterThanOrEqualUtil.js";

function distribute(calculator) {
  return (value, ratios) => {
    let equalFn = EqualUtil.equal(calculator);
    let greaterThanFn = GreaterThanUtil.greaterThan(calculator);
    let lessThanFn = LessThanUtil.lessThan(calculator);
    let greaterThanOrEqualFn = GreaterThanOrEqualUtil.greaterThanOrEqual(calculator);
    let zero = calculator.zero();
    let one = calculator.increment(zero);
    let total = Js_array.reduce((a, b) => calculator.add(a, b), zero, ratios);
    if (equalFn(total, zero)) {
      return ratios;
    }
    let remainder = {
      contents: value
    };
    let shares = Js_array.map(ratio => {
      let share = calculator.integerDivide(calculator.multiply(value, ratio), total);
      remainder.contents = calculator.subtract(remainder.contents, share);
      return share;
    }, ratios);
    let isPositive = greaterThanOrEqualFn(value, zero);
    let compare = isPositive ? greaterThanFn : lessThanFn;
    let amount = isPositive ? one : calculator.decrement(zero);
    let i = 0;
    while (compare(remainder.contents, zero)) {
      let currentIndex = Primitive_int.mod_(i, ratios.length);
      let ratio = Stdlib_Option.getOr(ratios[currentIndex], zero);
      if (!equalFn(ratio, zero)) {
        let currentShare = Stdlib_Option.getOr(shares[currentIndex], zero);
        let newShare = calculator.add(currentShare, amount);
        shares[currentIndex] = newShare;
        remainder.contents = calculator.subtract(remainder.contents, amount);
      }
      i = i + 1 | 0;
    };
    return shares;
  };
}

export {
  distribute,
}
/* No side effect */
