// Generated by ReScript, PLEASE EDIT WITH CARE


function equal(calculator) {
  return (subject, comparator) => calculator.compare(subject, comparator) === 0;
}

export {
  equal,
}
/* No side effect */
