// Generated by ReScript, PLEASE EDIT WITH CARE


function greaterThan(calculator) {
  return (subject, comparator) => calculator.compare(subject, comparator) === 1;
}

export {
  greaterThan,
}
/* No side effect */
