// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Absolute from "./absolute.js";

function isHalf(calculator) {
  let absoluteFn = Absolute.absolute(calculator);
  return (input, total) => {
    let remainder = absoluteFn(calculator.modulo(input, total));
    let difference = calculator.subtract(total, remainder);
    return calculator.compare(difference, remainder) === 0;
  };
}

export {
  isHalf,
}
/* No side effect */
