// Generated by ReScript, PLEASE EDIT WITH CARE


function lessThan(calculator) {
  return (subject, comparator) => calculator.compare(subject, comparator) === -1;
}

export {
  lessThan,
}
/* No side effect */
