// Generated by ReScript, PLEASE EDIT WITH CARE

import * as EqualUtil from "./equalUtil.js";
import * as LessThanUtil from "./lessThanUtil.js";

function lessThanOrEqual(calculator) {
  let lessThanFn = LessThanUtil.lessThan(calculator);
  let equalFn = EqualUtil.equal(calculator);
  return (subject, comparator) => {
    if (lessThanFn(subject, comparator)) {
      return true;
    } else {
      return equalFn(subject, comparator);
    }
  };
}

export {
  lessThanOrEqual,
}
/* No side effect */
