// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Add from "./api/add.js";
import * as Equal from "./api/equal.js";
import * as IsZero from "./api/isZero.js";
import * as Compare from "./api/compare.js";
import * as Convert from "./api/convert.js";
import * as Maximum from "./api/maximum.js";
import * as Minimum from "./api/minimum.js";
import * as ToUnits from "./api/toUnits.js";
import * as Allocate from "./api/allocate.js";
import * as LessThan from "./api/lessThan.js";
import * as Multiply from "./api/multiply.js";
import * as Subtract from "./api/subtract.js";
import * as ToDecimal from "./api/toDecimal.js";
import * as TrimScale from "./api/trimScale.js";
import * as IsNegative from "./api/isNegative.js";
import * as IsPositive from "./api/isPositive.js";
import * as ToSnapshot from "./api/toSnapshot.js";
import * as GreaterThan from "./api/greaterThan.js";
import * as HaveSameAmount from "./api/haveSameAmount.js";
import * as NormalizeScale from "./api/normalizeScale.js";
import * as TransformScale from "./api/transformScale.js";
import * as LessThanOrEqual from "./api/lessThanOrEqual.js";
import * as HaveSameCurrency from "./api/haveSameCurrency.js";
import * as GreaterThanOrEqual from "./api/greaterThanOrEqual.js";

let unsafeAdd = Add.unsafeAdd;

let safeAdd = Add.safeAdd;

let unsafeAllocate = Allocate.unsafeAllocate;

let safeAllocate = Allocate.safeAllocate;

let unsafeCompare = Compare.unsafeCompare;

let safeCompare = Compare.safeCompare;

let convert = Convert.convert;

let equal = Equal.equal;

let unsafeGreaterThan = GreaterThan.unsafeGreaterThan;

let safeGreaterThan = GreaterThan.safeGreaterThan;

let unsafeGreaterThanOrEqual = GreaterThanOrEqual.unsafeGreaterThanOrEqual;

let safeGreaterThanOrEqual = GreaterThanOrEqual.safeGreaterThanOrEqual;

let haveSameAmount = HaveSameAmount.haveSameAmount;

let haveSameCurrency = HaveSameCurrency.haveSameCurrency;

let isNegative = IsNegative.isNegative;

let isPositive = IsPositive.isPositive;

let isZero = IsZero.isZero;

let unsafeLessThan = LessThan.unsafeLessThan;

let safeLessThan = LessThan.safeLessThan;

let unsafeLessThanOrEqual = LessThanOrEqual.unsafeLessThanOrEqual;

let safeLessThanOrEqual = LessThanOrEqual.safeLessThanOrEqual;

let unsafeMaximum = Maximum.unsafeMaximum;

let safeMaximum = Maximum.safeMaximum;

let unsafeMinimum = Minimum.unsafeMinimum;

let safeMinimum = Minimum.safeMinimum;

let multiply = Multiply.multiply;

let normalizeScale = NormalizeScale.normalizeScale;

let unsafeSubtract = Subtract.unsafeSubtract;

let safeSubtract = Subtract.safeSubtract;

let getDecimal = ToDecimal.getDecimal;

let toDecimal = ToDecimal.toDecimal;

let toSnapshot = ToSnapshot.toSnapshot;

let toUnits = ToUnits.toUnits;

let transformScale = TransformScale.transformScale;

let trimScale = TrimScale.trimScale;

export {
  unsafeAdd,
  safeAdd,
  unsafeAllocate,
  safeAllocate,
  unsafeCompare,
  safeCompare,
  convert,
  equal,
  unsafeGreaterThan,
  safeGreaterThan,
  unsafeGreaterThanOrEqual,
  safeGreaterThanOrEqual,
  haveSameAmount,
  haveSameCurrency,
  isNegative,
  isPositive,
  isZero,
  unsafeLessThan,
  safeLessThan,
  unsafeLessThanOrEqual,
  safeLessThanOrEqual,
  unsafeMaximum,
  safeMaximum,
  unsafeMinimum,
  safeMinimum,
  multiply,
  normalizeScale,
  unsafeSubtract,
  safeSubtract,
  getDecimal,
  toDecimal,
  toSnapshot,
  toUnits,
  transformScale,
  trimScale,
}
/* No side effect */
