// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Aed from "./aed.js";
import * as Afn from "./afn.js";
import * as All from "./all.js";
import * as Amd from "./amd.js";
import * as Ang from "./ang.js";
import * as Aoa from "./aoa.js";
import * as Ars from "./ars.js";
import * as Aud from "./aud.js";
import * as Awg from "./awg.js";
import * as Azn from "./azn.js";
import * as Bam from "./bam.js";
import * as Bbd from "./bbd.js";
import * as Bdt from "./bdt.js";
import * as Bgn from "./bgn.js";
import * as Bhd from "./bhd.js";
import * as Bif from "./bif.js";
import * as Bmd from "./bmd.js";
import * as Bnd from "./bnd.js";
import * as Bob from "./bob.js";
import * as Bov from "./bov.js";
import * as Brl from "./brl.js";
import * as Bsd from "./bsd.js";
import * as Btn from "./btn.js";
import * as Bwp from "./bwp.js";
import * as Byn from "./byn.js";
import * as Bzd from "./bzd.js";
import * as Cad from "./cad.js";
import * as Cdf from "./cdf.js";
import * as Che from "./che.js";
import * as Chf from "./chf.js";
import * as Chw from "./chw.js";
import * as Clf from "./clf.js";
import * as Clp from "./clp.js";
import * as Cny from "./cny.js";
import * as Cop from "./cop.js";
import * as Cou from "./cou.js";
import * as Crc from "./crc.js";
import * as Cuc from "./cuc.js";
import * as Cup from "./cup.js";
import * as Cve from "./cve.js";
import * as Czk from "./czk.js";
import * as Djf from "./djf.js";
import * as Dkk from "./dkk.js";
import * as Dop from "./dop.js";
import * as Dzd from "./dzd.js";
import * as Egp from "./egp.js";
import * as Ern from "./ern.js";
import * as Etb from "./etb.js";
import * as Eur from "./eur.js";
import * as Fjd from "./fjd.js";
import * as Fkp from "./fkp.js";
import * as Gbp from "./gbp.js";
import * as Gel from "./gel.js";
import * as Ghs from "./ghs.js";
import * as Gip from "./gip.js";
import * as Gmd from "./gmd.js";
import * as Gnf from "./gnf.js";
import * as Gtq from "./gtq.js";
import * as Gyd from "./gyd.js";
import * as Hkd from "./hkd.js";
import * as Hnl from "./hnl.js";
import * as Hrk from "./hrk.js";
import * as Htg from "./htg.js";
import * as Huf from "./huf.js";
import * as Idr from "./idr.js";
import * as Ils from "./ils.js";
import * as Inr from "./inr.js";
import * as Iqd from "./iqd.js";
import * as Irr from "./irr.js";
import * as Isk from "./isk.js";
import * as Jmd from "./jmd.js";
import * as Jod from "./jod.js";
import * as Jpy from "./jpy.js";
import * as Kes from "./kes.js";
import * as Kgs from "./kgs.js";
import * as Khr from "./khr.js";
import * as Kmf from "./kmf.js";
import * as Kpw from "./kpw.js";
import * as Krw from "./krw.js";
import * as Kwd from "./kwd.js";
import * as Kyd from "./kyd.js";
import * as Kzt from "./kzt.js";
import * as Lak from "./lak.js";
import * as Lbp from "./lbp.js";
import * as Lkr from "./lkr.js";
import * as Lrd from "./lrd.js";
import * as Lsl from "./lsl.js";
import * as Lyd from "./lyd.js";
import * as Mad from "./mad.js";
import * as Mdl from "./mdl.js";
import * as Mga from "./mga.js";
import * as Mkd from "./mkd.js";
import * as Mmk from "./mmk.js";
import * as Mnt from "./mnt.js";
import * as Mop from "./mop.js";
import * as Mru from "./mru.js";
import * as Mur from "./mur.js";
import * as Mvr from "./mvr.js";
import * as Mwk from "./mwk.js";
import * as Mxn from "./mxn.js";
import * as Mxv from "./mxv.js";
import * as Myr from "./myr.js";
import * as Mzn from "./mzn.js";
import * as Nad from "./nad.js";
import * as Ngn from "./ngn.js";
import * as Nio from "./nio.js";
import * as Nok from "./nok.js";
import * as Npr from "./npr.js";
import * as Nzd from "./nzd.js";
import * as Omr from "./omr.js";
import * as Pab from "./pab.js";
import * as Pen from "./pen.js";
import * as Pgk from "./pgk.js";
import * as Php from "./php.js";
import * as Pkr from "./pkr.js";
import * as Pln from "./pln.js";
import * as Pyg from "./pyg.js";
import * as Qar from "./qar.js";
import * as Ron from "./ron.js";
import * as Rsd from "./rsd.js";
import * as Rub from "./rub.js";
import * as Rwf from "./rwf.js";
import * as Sar from "./sar.js";
import * as Sbd from "./sbd.js";
import * as Scr from "./scr.js";
import * as Sdg from "./sdg.js";
import * as Sek from "./sek.js";
import * as Sgd from "./sgd.js";
import * as Shp from "./shp.js";
import * as Sll from "./sll.js";
import * as Sos from "./sos.js";
import * as Srd from "./srd.js";
import * as Ssp from "./ssp.js";
import * as Stn from "./stn.js";
import * as Svc from "./svc.js";
import * as Syp from "./syp.js";
import * as Szl from "./szl.js";
import * as Thb from "./thb.js";
import * as Tjs from "./tjs.js";
import * as Tmt from "./tmt.js";
import * as Tnd from "./tnd.js";
import * as Top from "./top.js";
import * as Try from "./try.js";
import * as Ttd from "./ttd.js";
import * as Twd from "./twd.js";
import * as Tzs from "./tzs.js";
import * as Uah from "./uah.js";
import * as Ugx from "./ugx.js";
import * as Usd from "./usd.js";
import * as Usn from "./usn.js";
import * as Uyi from "./uyi.js";
import * as Uyu from "./uyu.js";
import * as Uyw from "./uyw.js";
import * as Uzs from "./uzs.js";
import * as Ves from "./ves.js";
import * as Vnd from "./vnd.js";
import * as Vuv from "./vuv.js";
import * as Wst from "./wst.js";
import * as Xaf from "./xaf.js";
import * as Xcd from "./xcd.js";
import * as Xof from "./xof.js";
import * as Xpf from "./xpf.js";
import * as Yer from "./yer.js";
import * as Zar from "./zar.js";
import * as Zmw from "./zmw.js";
import * as Zwl from "./zwl.js";

let aed = Aed.aed;

let afn = Afn.afn;

let all = All.all;

let amd = Amd.amd;

let ang = Ang.ang;

let aoa = Aoa.aoa;

let ars = Ars.ars;

let aud = Aud.aud;

let awg = Awg.awg;

let azn = Azn.azn;

let bam = Bam.bam;

let bbd = Bbd.bbd;

let bdt = Bdt.bdt;

let bgn = Bgn.bgn;

let bhd = Bhd.bhd;

let bif = Bif.bif;

let bmd = Bmd.bmd;

let bnd = Bnd.bnd;

let bob = Bob.bob;

let bov = Bov.bov;

let brl = Brl.brl;

let bsd = Bsd.bsd;

let btn = Btn.btn;

let bwp = Bwp.bwp;

let byn = Byn.byn;

let bzd = Bzd.bzd;

let cad = Cad.cad;

let cdf = Cdf.cdf;

let che = Che.che;

let chf = Chf.chf;

let chw = Chw.chw;

let clf = Clf.clf;

let clp = Clp.clp;

let cny = Cny.cny;

let cop = Cop.cop;

let cou = Cou.cou;

let crc = Crc.crc;

let cuc = Cuc.cuc;

let cup = Cup.cup;

let cve = Cve.cve;

let czk = Czk.czk;

let djf = Djf.djf;

let dkk = Dkk.dkk;

let dop = Dop.dop;

let dzd = Dzd.dzd;

let egp = Egp.egp;

let ern = Ern.ern;

let etb = Etb.etb;

let eur = Eur.eur;

let fjd = Fjd.fjd;

let fkp = Fkp.fkp;

let gbp = Gbp.gbp;

let gel = Gel.gel;

let ghs = Ghs.ghs;

let gip = Gip.gip;

let gmd = Gmd.gmd;

let gnf = Gnf.gnf;

let gtq = Gtq.gtq;

let gyd = Gyd.gyd;

let hkd = Hkd.hkd;

let hnl = Hnl.hnl;

let hrk = Hrk.hrk;

let htg = Htg.htg;

let huf = Huf.huf;

let idr = Idr.idr;

let ils = Ils.ils;

let inr = Inr.inr;

let iqd = Iqd.iqd;

let irr = Irr.irr;

let isk = Isk.isk;

let jmd = Jmd.jmd;

let jod = Jod.jod;

let jpy = Jpy.jpy;

let kes = Kes.kes;

let kgs = Kgs.kgs;

let khr = Khr.khr;

let kmf = Kmf.kmf;

let kpw = Kpw.kpw;

let krw = Krw.krw;

let kwd = Kwd.kwd;

let kyd = Kyd.kyd;

let kzt = Kzt.kzt;

let lak = Lak.lak;

let lbp = Lbp.lbp;

let lkr = Lkr.lkr;

let lrd = Lrd.lrd;

let lsl = Lsl.lsl;

let lyd = Lyd.lyd;

let mad = Mad.mad;

let mdl = Mdl.mdl;

let mga = Mga.mga;

let mkd = Mkd.mkd;

let mmk = Mmk.mmk;

let mnt = Mnt.mnt;

let mop = Mop.mop;

let mru = Mru.mru;

let mur = Mur.mur;

let mvr = Mvr.mvr;

let mwk = Mwk.mwk;

let mxn = Mxn.mxn;

let mxv = Mxv.mxv;

let myr = Myr.myr;

let mzn = Mzn.mzn;

let nad = Nad.nad;

let ngn = Ngn.ngn;

let nio = Nio.nio;

let nok = Nok.nok;

let npr = Npr.npr;

let nzd = Nzd.nzd;

let omr = Omr.omr;

let pab = Pab.pab;

let pen = Pen.pen;

let pgk = Pgk.pgk;

let php = Php.php;

let pkr = Pkr.pkr;

let pln = Pln.pln;

let pyg = Pyg.pyg;

let qar = Qar.qar;

let ron = Ron.ron;

let rsd = Rsd.rsd;

let rub = Rub.rub;

let rwf = Rwf.rwf;

let sar = Sar.sar;

let sbd = Sbd.sbd;

let scr = Scr.scr;

let sdg = Sdg.sdg;

let sek = Sek.sek;

let sgd = Sgd.sgd;

let shp = Shp.shp;

let sll = Sll.sll;

let sos = Sos.sos;

let srd = Srd.srd;

let ssp = Ssp.ssp;

let stn = Stn.stn;

let svc = Svc.svc;

let syp = Syp.syp;

let szl = Szl.szl;

let thb = Thb.thb;

let tjs = Tjs.tjs;

let tmt = Tmt.tmt;

let tnd = Tnd.tnd;

let top = Top.top;

let $$try = Try.$$try;

let ttd = Ttd.ttd;

let twd = Twd.twd;

let tzs = Tzs.tzs;

let uah = Uah.uah;

let ugx = Ugx.ugx;

let usd = Usd.usd;

let usn = Usn.usn;

let uyi = Uyi.uyi;

let uyu = Uyu.uyu;

let uyw = Uyw.uyw;

let uzs = Uzs.uzs;

let ves = Ves.ves;

let vnd = Vnd.vnd;

let vuv = Vuv.vuv;

let wst = Wst.wst;

let xaf = Xaf.xaf;

let xcd = Xcd.xcd;

let xof = Xof.xof;

let xpf = Xpf.xpf;

let yer = Yer.yer;

let zar = Zar.zar;

let zmw = Zmw.zmw;

let zwl = Zwl.zwl;

export {
  aed,
  afn,
  all,
  amd,
  ang,
  aoa,
  ars,
  aud,
  awg,
  azn,
  bam,
  bbd,
  bdt,
  bgn,
  bhd,
  bif,
  bmd,
  bnd,
  bob,
  bov,
  brl,
  bsd,
  btn,
  bwp,
  byn,
  bzd,
  cad,
  cdf,
  che,
  chf,
  chw,
  clf,
  clp,
  cny,
  cop,
  cou,
  crc,
  cuc,
  cup,
  cve,
  czk,
  djf,
  dkk,
  dop,
  dzd,
  egp,
  ern,
  etb,
  eur,
  fjd,
  fkp,
  gbp,
  gel,
  ghs,
  gip,
  gmd,
  gnf,
  gtq,
  gyd,
  hkd,
  hnl,
  hrk,
  htg,
  huf,
  idr,
  ils,
  inr,
  iqd,
  irr,
  isk,
  jmd,
  jod,
  jpy,
  kes,
  kgs,
  khr,
  kmf,
  kpw,
  krw,
  kwd,
  kyd,
  kzt,
  lak,
  lbp,
  lkr,
  lrd,
  lsl,
  lyd,
  mad,
  mdl,
  mga,
  mkd,
  mmk,
  mnt,
  mop,
  mru,
  mur,
  mvr,
  mwk,
  mxn,
  mxv,
  myr,
  mzn,
  nad,
  ngn,
  nio,
  nok,
  npr,
  nzd,
  omr,
  pab,
  pen,
  pgk,
  php,
  pkr,
  pln,
  pyg,
  qar,
  ron,
  rsd,
  rub,
  rwf,
  sar,
  sbd,
  scr,
  sdg,
  sek,
  sgd,
  shp,
  sll,
  sos,
  srd,
  ssp,
  stn,
  svc,
  syp,
  szl,
  thb,
  tjs,
  tmt,
  tnd,
  top,
  $$try,
  ttd,
  twd,
  tzs,
  uah,
  ugx,
  usd,
  usn,
  uyi,
  uyu,
  uyw,
  uzs,
  ves,
  vnd,
  vuv,
  wst,
  xaf,
  xcd,
  xof,
  xpf,
  yer,
  zar,
  zmw,
  zwl,
}
/* No side effect */
