// Generated by ReScript, PLEASE EDIT WITH CARE

import * as EqualUtil from "./equalUtil.js";
import * as LessThanUtil from "./lessThanUtil.js";

function absolute(calculator) {
  let equalFn = EqualUtil.equal(calculator);
  let lessThanFn = LessThanUtil.lessThan(calculator);
  let zero = calculator.zero();
  return input => {
    if (equalFn(input, zero)) {
      return zero;
    }
    if (!lessThanFn(input, zero)) {
      return input;
    }
    let minusOne = calculator.decrement(zero);
    return calculator.multiply(minusOne, input);
  };
}

export {
  absolute,
}
/* No side effect */
