// Generated by ReScript, PLEASE EDIT WITH CARE


function compare(calculator) {
  return (subject, comparator) => calculator.compare(subject, comparator);
}

export {
  compare,
}
/* No side effect */
