// Generated by ReScript, PLEASE EDIT WITH CARE


function countTrailingZeros(calculator) {
  return (input, base) => {
    let zero = calculator.zero();
    if (calculator.compare(zero, input) === 0) {
      return calculator.zero();
    }
    let _temp = input;
    let _i = zero;
    while (true) {
      let i = _i;
      let temp = _temp;
      if (calculator.compare(calculator.modulo(temp, base), zero) !== 0) {
        return i;
      }
      _i = calculator.increment(i);
      _temp = calculator.integerDivide(temp, base);
      continue;
    };
  };
}

export {
  countTrailingZeros,
}
/* No side effect */
