// Generated by ReScript, PLEASE EDIT WITH CARE

import * as IsScaledAmount from "./isScaledAmount.js";

function getAmountAndScale(value, zero) {
  let maybeScaled = IsScaledAmount.fromValue(value);
  if (maybeScaled.TAG !== "ScaledAmount") {
    return {
      amount: maybeScaled._0,
      scale: zero
    };
  }
  let scaledValue = maybeScaled._0;
  return {
    amount: scaledValue.amount,
    scale: scaledValue.scale
  };
}

export {
  getAmountAndScale,
}
/* No side effect */
