// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Stdlib_Array from "@rescript/runtime/lib/es6/Stdlib_Array.js";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

function getDivisors(calculator) {
  return bases => Stdlib_Array.reduceWithIndex(bases, [], (divisors, param, i) => {
    let slice = bases.slice(i);
    let first = slice[0];
    if (first === undefined) {
      return divisors;
    }
    let rest = slice.slice(1);
    let divisor = Stdlib_Array.reduce(rest, Primitive_option.valFromOption(first), (acc, curr) => calculator.multiply(acc, curr));
    return divisors.concat([divisor]);
  });
}

export {
  getDivisors,
}
/* No side effect */
