// Generated by ReScript, PLEASE EDIT WITH CARE

import * as EqualUtil from "./equalUtil.js";
import * as GreaterThanUtil from "./greaterThanUtil.js";

function greaterThanOrEqual(calculator) {
  let greaterThanFn = GreaterThanUtil.greaterThan(calculator);
  let equalFn = EqualUtil.equal(calculator);
  return (subject, comparator) => {
    if (greaterThanFn(subject, comparator)) {
      return true;
    } else {
      return equalFn(subject, comparator);
    }
  };
}

export {
  greaterThanOrEqual,
}
/* No side effect */
