// Generated by ReScript, PLEASE EDIT WITH CARE


function isEven(calculator) {
  let zero = calculator.zero();
  let two = calculator.increment(calculator.increment(zero));
  return input => calculator.compare(calculator.modulo(input, two), zero) === 0;
}

export {
  isEven,
}
/* No side effect */
