// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Stdlib_JsError from "@rescript/runtime/lib/es6/Stdlib_JsError.js";

function isScaledAmount(value) {
  return value.TAG === "ScaledAmount";
}

function fromValue(value) {
  let match = typeof value;
  if (match !== "object") {
    if (match === "number") {
      return {
        TAG: "Amount",
        _0: value
      };
    } else {
      return Stdlib_JsError.throwWithMessage("Expected either a number or a scaled amount");
    }
  }
  if (typeof value !== "object" || value === null || Array.isArray(value)) {
    return {
      TAG: "Amount",
      _0: value
    };
  }
  let amount = value.amount;
  if (typeof amount === "number") {
    let scale = value.scale;
    if (typeof scale === "number") {
      return {
        TAG: "ScaledAmount",
        _0: {
          amount: amount,
          scale: scale
        }
      };
    }
  }
  let amount$1 = value.amount;
  if (typeof amount$1 === "number") {
    return {
      TAG: "ScaledAmount",
      _0: {
        amount: amount$1,
        scale: 0.0
      }
    };
  } else {
    return {
      TAG: "Amount",
      _0: value
    };
  }
}

export {
  isScaledAmount,
  fromValue,
}
/* No side effect */
