// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Js_array from "@rescript/runtime/lib/es6/Js_array.js";
import * as LessThanUtil from "./lessThanUtil.js";
import * as Stdlib_JsError from "@rescript/runtime/lib/es6/Stdlib_JsError.js";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

function maximum(calculator) {
  let lessThanFn = LessThanUtil.lessThan(calculator);
  return values => {
    let first = values[0];
    if (first !== undefined) {
      return Js_array.reduce((acc, curr) => {
        if (lessThanFn(acc, curr)) {
          return curr;
        } else {
          return acc;
        }
      }, Primitive_option.valFromOption(first), values.slice(1));
    } else {
      return Stdlib_JsError.throwWithMessage("Cannot find maximum of empty array");
    }
  };
}

export {
  maximum,
}
/* No side effect */
