// Generated by ReScript, PLEASE EDIT WITH CARE

import * as EqualUtil from "./equalUtil.js";
import * as LessThanUtil from "./lessThanUtil.js";

function sign(calculator) {
  let equalFn = EqualUtil.equal(calculator);
  let lessThanFn = LessThanUtil.lessThan(calculator);
  let zero = calculator.zero();
  return input => {
    if (equalFn(input, zero)) {
      return zero;
    }
    let one = calculator.increment(zero);
    let minusOne = calculator.decrement(zero);
    if (lessThanFn(input, zero)) {
      return minusOne;
    } else {
      return one;
    }
  };
}

export {
  sign,
}
/* No side effect */
