name: Check Pull Request

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - '**/*'

env:
  # environment variables to config `turbo` to use the local cache server
  TURBO_API: 'http://127.0.0.1:9080'
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: 'dinero'
  # Used by scripts/build-types.mjs
  CI: true

permissions:
  checks: write
  contents: read
  statuses: write
  pull-requests: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Prepare Environment
        uses: ./.github/actions/turbo
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        run: yarn build
  lint:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Prepare Environment
        uses: ./.github/actions/turbo
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Lint
        run: yarn lint
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Prepare Environment
        uses: ./.github/actions/turbo
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Test
        run: yarn test
  test-types:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Prepare Environment
        uses: ./.github/actions/turbo
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Test types
        run: yarn test:types
  test-size:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Prepare Environment
        uses: ./.github/actions/turbo
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Test bundle size
        run: yarn test:size
