name: On Pull Request

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - 'ci/*'

permissions:
  checks: write
  contents: read
  statuses: write
  pull-requests: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./actions/turbo
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        run: yarn build
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./actions/turbo
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Lint
        run: yarn lint
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./actions/turbo
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Test
        run: yarn test:ci
  test-types:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./actions/turbo
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Test types
        run: yarn test:types
  test-size:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./actions/turbo
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Test bundle size
        run: yarn test:size
